<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Controller;
use App\Models\Guardian;
use App\Providers\RouteServiceProvider;
use App\Models\User;
use Illuminate\Foundation\Auth\RegistersUsers;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;
use Spatie\Permission\Models\Role;

class RegisterController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Register Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users as well as their
    | validation and creation. By default this controller uses a trait to
    | provide this functionality without requiring any additional code.
    |
    */

    use RegistersUsers;

    /**
     * Where to redirect users after registration.
     *
     * @var string
     */
    protected $redirectTo = RouteServiceProvider::HOME;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('guest');
    }

    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return \App\Models\User
     */
    protected function create(array $data)
    {
        // Create Parent
        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'role' => 'guardian',
            'password' => Hash::make($data['password']),
        ]);
        $user->assignRole('Guardian');

        $parent_data['user_id'] = $user->id;
        $parent_data['gender'] = 'male';
        $parent_data['phone'] = $data['phone'];
        $parent_data['session_id'] = currentSession();
        $guardian = Guardian::create($parent_data);

        if (abs($data['phone'])>0) {
            $date = time();
            $hari = date("D");
            switch ($hari) {
                case 'Sun':
                    $hari_ini = "Minggu";
                    break;
                case 'Mon':
                    $hari_ini = "Senin";
                    break;
                case 'Tue':
                    $hari_ini = "Selasa";
                    break;
                case 'Wed':
                    $hari_ini = "Rabu";
                    break;
                case 'Thu':
                    $hari_ini = "Kamis";
                    break;
                case 'Fri':
                    $hari_ini = "Jumat";
                    break;
                case 'Sat':
                    $hari_ini = "Sabtu";
                    break;
                default:
                    $hari_ini = "Tidak di ketahui";
                    break;
            }
            $data = [
                'api_key' => 'K1LU0bkB1ndRUqBTFz3L4Zgyqhc1Zx',
                'sender'  => '6289635850446',
                'number'  => $data['phone'],
                'message' => '
بِسْــــــــــــــــــمِ اﷲِالرَّحْمَنِ اارَّحِيم

Bandung, ' . date("d M Y", $date) . '


Segala puji milik Allah Rabb semesta alam, Shalawat dan salam tercurah limpah pada Baginda Muhammad Shalallahu alaihi wasallam.

Bapak/ Ibu ' . ucfirst($data['name']) . ', terimakasih telah sudah mendaftar di Form PPDB ini, informasi lebih lanjut akan kami infokan berikutnya.

Terimakasih.



Sistem Informasi Muhammadiyah 3.
WhatsApp Notification Generated by Fathforce Education System.

',
            ];
            $curl = curl_init();
            curl_setopt_array(
                $curl,
                array(
                    CURLOPT_URL => 'http://wa.fathforce.com/send-message',
                    CURLOPT_RETURNTRANSFER => true,
                    CURLOPT_ENCODING => '',
                    CURLOPT_MAXREDIRS => 10,
                    CURLOPT_TIMEOUT => 0,
                    CURLOPT_FOLLOWLOCATION => true,
                    CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
                    CURLOPT_CUSTOMREQUEST => 'POST',
                    CURLOPT_POSTFIELDS => json_encode($data),
                    CURLOPT_HTTPHEADER => array(
                        'Content-Type: application/json'
                    ),
                )
            );

            $response = curl_exec($curl);

            curl_close($curl);
        }

        // Create
        // $role =  Role::findByName('writer');
        // dd($role);
        // $user->assignRole($role);

        return $user;
    }
}
